[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd neverness-builds && npm install']

[phases.build]
cmds = ['cd neverness-builds && npm run build']

[start]
cmd = 'cd neverness-builds && npm run preview -- --host 0.0.0.0 --port $PORT'
